package gocurrency

// Countries holds the raw data
var Countries = []Country{
	{
		Code:           "AF",
		Currency:       "AFN",
		CurrencySymbol: "؋",
		Phone:          "+93",
		Name:           "Afghanistan",
		NameZh:         "阿富汗",
	},
	{
		Code:           "AL",
		Currency:       "ALL",
		CurrencySymbol: "L",
		Phone:          "+355",
		Name:           "Albania",
		NameZh:         "阿尔巴尼亚",
	},
	{
		Code:           "DZ",
		Currency:       "DZD",
		CurrencySymbol: "دج",
		Phone:          "+213",
		Name:           "Algeria",
		NameZh:         "阿尔及利亚",
	},
	{
		Code:           "AS",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+1684",
		Name:           "American Samoa",
		NameZh:         "美属萨摩亚",
	},
	{
		Code:           "AD",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+376",
		Name:           "Andorra",
		NameZh:         "安道尔",
	},
	{
		Code:           "AO",
		Currency:       "AOA",
		CurrencySymbol: "Kz",
		Phone:          "+244",
		Name:           "Angola",
		NameZh:         "安哥拉",
	},
	{
		Code:           "AI",
		Currency:       "XCD",
		CurrencySymbol: "$",
		Phone:          "+1264",
		Name:           "Anguilla",
		NameZh:         "安圭拉",
	},
	{
		Code:           "AQ",
		Currency:       "",
		CurrencySymbol: "$",
		Phone:          "+672",
		Name:           "Antarctica",
		NameZh:         "南极洲",
	},
	{
		Code:           "AG",
		Currency:       "XCD",
		CurrencySymbol: "$",
		Phone:          "+1268",
		Name:           "Antigua and Barbuda",
		NameZh:         "安提瓜和巴布达",
	},
	{
		Code:           "AR",
		Currency:       "ARS",
		CurrencySymbol: "$",
		Phone:          "+54",
		Name:           "Argentina",
		NameZh:         "阿根廷",
	},
	{
		Code:           "AM",
		Currency:       "AMD",
		CurrencySymbol: "֏",
		Phone:          "+374",
		Name:           "Armenia",
		NameZh:         "亚美尼亚",
	},
	{
		Code:           "AW",
		Currency:       "AWG",
		CurrencySymbol: "ƒ",
		Phone:          "+297",
		Name:           "Aruba",
		NameZh:         "阿鲁巴",
	},
	{
		Code:           "AU",
		Currency:       "AUD",
		CurrencySymbol: "$",
		Phone:          "+61",
		Name:           "Australia",
		NameZh:         "澳大利亚",
	},
	{
		Code:           "AT",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+43",
		Name:           "Austria",
		NameZh:         "奥地利",
	},
	{
		Code:           "AZ",
		Currency:       "AZN",
		CurrencySymbol: "₼",
		Phone:          "+994",
		Name:           "Azerbaijan",
		NameZh:         "阿塞拜疆",
	},
	{
		Code:           "BH",
		Currency:       "BHD",
		CurrencySymbol: ".د.ب",
		Phone:          "+973",
		Name:           "Bahrain",
		NameZh:         "巴林",
	},
	{
		Code:           "BS",
		Currency:       "BSD",
		CurrencySymbol: "$",
		Phone:          "+1242",
		Name:           "The Bahamas",
		NameZh:         "巴哈马",
	},
	{
		Code:           "BD",
		Currency:       "BDT",
		CurrencySymbol: "৳",
		Phone:          "+880",
		Name:           "Bangladesh",
		NameZh:         "孟加拉国",
	},
	{
		Code:           "BB",
		Currency:       "BBD",
		CurrencySymbol: "$",
		Phone:          "+1 246",
		Name:           "Barbados",
		NameZh:         "巴巴多斯",
	},
	{
		Code:           "BY",
		Currency:       "BYR",
		CurrencySymbol: "Br",
		Phone:          "+375",
		Name:           "Belarus",
		NameZh:         "白俄罗斯",
	},
	{
		Code:           "BE",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+32",
		Name:           "Belgium",
		NameZh:         "比利时",
	},
	{
		Code:           "BZ",
		Currency:       "BZD",
		CurrencySymbol: "BZ$",
		Phone:          "+501",
		Name:           "Belize",
		NameZh:         "伯利兹",
	},
	{
		Code:           "BJ",
		Currency:       "XOF",
		CurrencySymbol: "CFA",
		Phone:          "+229",
		Name:           "Benin",
		NameZh:         "贝宁",
	},
	{
		Code:           "BM",
		Currency:       "BMD",
		CurrencySymbol: "$",
		Phone:          "+1441",
		Name:           "Bermuda",
		NameZh:         "百慕大",
	},
	{
		Code:           "BT",
		Currency:       "BTN",
		CurrencySymbol: "Nu.",
		Phone:          "+975",
		Name:           "Bhutan",
		NameZh:         "不丹",
	},
	{
		Code:           "BO",
		Currency:       "BOB",
		CurrencySymbol: "$b",
		Phone:          "+591",
		Name:           "Bolivia",
		NameZh:         "玻利维亚",
	},
	{
		Code:           "BQ",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+599",
		Name:           "Bonaire",
		NameZh:         "博内尔",
	},
	{
		Code:           "BA",
		Currency:       "BAM",
		CurrencySymbol: "KM",
		Phone:          "+387",
		Name:           "Bosnia and Herzegovina",
		NameZh:         "波斯尼亚和黑塞哥维那",
	},
	{
		Code:           "BW",
		Currency:       "BWP",
		CurrencySymbol: "P",
		Phone:          "+267",
		Name:           "Botswana",
		NameZh:         "博茨瓦纳",
	},
	{
		Code:           "BV",
		Currency:       "NOK",
		CurrencySymbol: "kr",
		Phone:          "+47",
		Name:           "Bouvet",
		NameZh:         "布韦岛",
	},
	{
		Code:           "BR",
		Currency:       "BRL",
		CurrencySymbol: "R$",
		Phone:          "+55",
		Name:           "Brazil",
		NameZh:         "巴西",
	},
	{
		Code:           "IO",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+246",
		Name:           "British Indian Ocean Territory",
		NameZh:         "英属印度洋领地",
	},
	{
		Code:           "VG",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+1284",
		Name:           "British Virgin Islands",
		NameZh:         "英属维尔京群岛",
	},
	{
		Code:           "BN",
		Currency:       "BND",
		CurrencySymbol: "$",
		Phone:          "+673",
		Name:           "Brunei",
		NameZh:         "文莱",
	},
	{
		Code:           "BG",
		Currency:       "BGN",
		CurrencySymbol: "лв",
		Phone:          "+359",
		Name:           "Bulgaria",
		NameZh:         "保加利亚",
	},
	{
		Code:           "BF",
		Currency:       "XOF",
		CurrencySymbol: "CFA",
		Phone:          "+226",
		Name:           "Burkina Faso",
		NameZh:         "布基纳法索",
	},
	{
		Code:           "MM",
		Currency:       "MMK",
		CurrencySymbol: "K",
		Phone:          "+95",
		Name:           "Myanmar",
		NameZh:         "缅甸",
	},
	{
		Code:           "BI",
		Currency:       "BIF",
		CurrencySymbol: "FBu",
		Phone:          "+257",
		Name:           "Burundi",
		NameZh:         "布隆迪",
	},
	{
		Code:           "KH",
		Currency:       "KHR",
		CurrencySymbol: "៛",
		Phone:          "+855",
		Name:           "Cambodia",
		NameZh:         "柬埔寨",
	},
	{
		Code:           "CM",
		Currency:       "XAF",
		CurrencySymbol: "FCFA",
		Phone:          "+237",
		Name:           "Cameroon",
		NameZh:         "喀麦隆",
	},
	{
		Code:           "CA",
		Currency:       "CAD",
		CurrencySymbol: "$",
		Phone:          "+1",
		Name:           "Canada",
		NameZh:         "加拿大",
	},
	{
		Code:           "CV",
		Currency:       "CVE",
		CurrencySymbol: "$",
		Phone:          "+238",
		Name:           "Cape Verde",
		NameZh:         "佛得角",
	},
	{
		Code:           "KY",
		Currency:       "KYD",
		CurrencySymbol: "$",
		Phone:          "+1345",
		Name:           "Cayman Islands",
		NameZh:         "开曼群岛",
	},
	{
		Code:           "CF",
		Currency:       "XAF",
		CurrencySymbol: "FCFA",
		Phone:          "+236",
		Name:           "Central African Republic",
		NameZh:         "中非共和国",
	},
	{
		Code:           "TD",
		Currency:       "XAF",
		CurrencySymbol: "FCFA",
		Phone:          "+235",
		Name:           "Chad",
		NameZh:         "乍得",
	},
	{
		Code:           "CL",
		Currency:       "CLP",
		CurrencySymbol: "$",
		Phone:          "+56",
		Name:           "Chile",
		NameZh:         "智利",
	},
	{
		Code:           "CN",
		Currency:       "CNY",
		CurrencySymbol: "¥",
		Phone:          "+86",
		Name:           "China",
		NameZh:         "中国",
	},
	{
		Code:           "CX",
		Currency:       "AUD",
		CurrencySymbol: "$",
		Phone:          "+61",
		Name:           "Christmas Island",
		NameZh:         "圣诞岛",
	},
	{
		Code:           "CC",
		Currency:       "AUD",
		CurrencySymbol: "$",
		Phone:          "+672",
		Name:           "Cocos-Keeling Islands",
		NameZh:         "科科斯（基林）群岛",
	},
	{
		Code:           "CO",
		Currency:       "COP",
		CurrencySymbol: "$",
		Phone:          "+57",
		Name:           "Colombia",
		NameZh:         "哥伦比亚",
	},
	{
		Code:           "KM",
		Currency:       "KMF",
		CurrencySymbol: "CF",
		Phone:          "+269",
		Name:           "Comoros",
		NameZh:         "科摩罗",
	},
	{
		Code:           "CG",
		Currency:       "XAF",
		CurrencySymbol: "FCFA",
		Phone:          "+242",
		Name:           "Congo",
		NameZh:         "刚果共和国",
	},
	{
		Code:           "CD",
		Currency:       "CDF",
		CurrencySymbol: "FC",
		Phone:          "+243",
		Name:           "Congo, Dem. Rep. of (Zaire)",
		NameZh:         "刚果民主共和国（扎伊尔）",
	},
	{
		Code:           "CK",
		Currency:       "NZD",
		CurrencySymbol: "$",
		Phone:          "+682",
		Name:           "Cook Islands",
		NameZh:         "库克群岛",
	},
	{
		Code:           "CR",
		Currency:       "CRC",
		CurrencySymbol: "₡",
		Phone:          "+506",
		Name:           "Costa Rica",
		NameZh:         "哥斯达黎加",
	},
	{
		Code:           "CI",
		Currency:       "XOF",
		CurrencySymbol: "CFA",
		Phone:          "+225",
		Name:           "Cote d'Ivoire",
		NameZh:         "科特迪瓦",
	},
	{
		Code:           "HR",
		Currency:       "HRK",
		CurrencySymbol: "kn",
		Phone:          "+385",
		Name:           "Croatia",
		NameZh:         "克罗地亚",
	},
	{
		Code:           "CW",
		Currency:       "ANG",
		CurrencySymbol: "ƒ",
		Phone:          "+599",
		Name:           "Curacao",
		NameZh:         "库拉索",
	},
	{
		Code:           "CU",
		Currency:       "CUP",
		CurrencySymbol: "₱",
		Phone:          "+53",
		Name:           "Cuba",
		NameZh:         "古巴",
	},
	{
		Code:           "CY",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+357",
		Name:           "Cyprus",
		NameZh:         "塞浦路斯",
	},
	{
		Code:           "CZ",
		Currency:       "CZK",
		CurrencySymbol: "Kč",
		Phone:          "+420",
		Name:           "Czech Republic",
		NameZh:         "捷克共和国",
	},
	{
		Code:           "DK",
		Currency:       "DKK",
		CurrencySymbol: "kr",
		Phone:          "+45",
		Name:           "Denmark",
		NameZh:         "丹麦",
	},
	{
		Code:           "DJ",
		Currency:       "DJF",
		CurrencySymbol: "Fdj",
		Phone:          "+253",
		Name:           "Djibouti",
		NameZh:         "吉布提",
	},
	{
		Code:           "DM",
		Currency:       "XCD",
		CurrencySymbol: "$",
		Phone:          "+1767",
		Name:           "Dominica",
		NameZh:         "多米尼克",
	},
	{
		Code:           "DO",
		Currency:       "DOP",
		CurrencySymbol: "RD$",
		Phone:          "+1809",
		Name:           "Dominican Republic",
		NameZh:         "多米尼加共和国",
	},
	{
		Code:           "TL",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+670",
		Name:           "East Timor",
		NameZh:         "东帝汶",
	},
	{
		Code:           "EC",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+593",
		Name:           "Ecuador",
		NameZh:         "厄瓜多尔",
	},
	{
		Code:           "EG",
		Currency:       "EGP",
		CurrencySymbol: "£",
		Phone:          "+20",
		Name:           "Egypt",
		NameZh:         "埃及",
	},
	{
		Code:           "SV",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+503",
		Name:           "El Salvador",
		NameZh:         "萨尔瓦多",
	},
	{
		Code:           "GQ",
		Currency:       "XAF",
		CurrencySymbol: "FCFA",
		Phone:          "+240",
		Name:           "Equatorial Guinea",
		NameZh:         "赤道几内亚",
	},
	{
		Code:           "ER",
		Currency:       "ERN",
		CurrencySymbol: "Nfk",
		Phone:          "+291",
		Name:           "Eritrea",
		NameZh:         "厄立特里亚",
	},
	{
		Code:           "EE",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+372",
		Name:           "Estonia",
		NameZh:         "爱沙尼亚",
	},
	{
		Code:           "ET",
		Currency:       "ETB",
		CurrencySymbol: "Br",
		Phone:          "+251",
		Name:           "Ethiopia",
		NameZh:         "埃塞俄比亚",
	},
	{
		Code:           "FK",
		Currency:       "FKP",
		CurrencySymbol: "£",
		Phone:          "+500",
		Name:           "Falkland Islands",
		NameZh:         "福克兰群岛",
	},
	{
		Code:           "FO",
		Currency:       "DKK",
		CurrencySymbol: "kr",
		Phone:          "+679",
		Name:           "Fiji",
		NameZh:         "斐济",
	},
	{
		Code:           "FI",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+358",
		Name:           "Finland",
		NameZh:         "芬兰",
	},
	{
		Code:           "FR",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+33",
		Name:           "France",
		NameZh:         "法国",
	},
	{
		Code:           "GF",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+594",
		Name:           "French Guiana",
		NameZh:         "法属圭亚那",
	},
	{
		Code:           "PF",
		Currency:       "XPF",
		CurrencySymbol: "₣",
		Phone:          "+689",
		Name:           "French Polynesia",
		NameZh:         "法属波利尼西亚",
	},
	{
		Code:           "TF",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+262",
		Name:           "French Southern and Antarctic Lands",
		NameZh:         "法属南部和南极领地",
	},
	{
		Code:           "GA",
		Currency:       "XAF",
		CurrencySymbol: "FCFA",
		Phone:          "+241",
		Name:           "Gabon",
		NameZh:         "加蓬",
	},
	{
		Code:           "GM",
		Currency:       "GMD",
		CurrencySymbol: "D",
		Phone:          "+220",
		Name:           "The Gambia",
		NameZh:         "冈比亚",
	},
	{
		Code:           "GE",
		Currency:       "GEL",
		CurrencySymbol: "₾",
		Phone:          "+995",
		Name:           "Georgia",
		NameZh:         "格鲁吉亚",
	},
	{
		Code:           "DE",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+49",
		Name:           "Germany",
		NameZh:         "德国",
	},
	{
		Code:           "GH",
		Currency:       "GHS",
		CurrencySymbol: "GH₵",
		Phone:          "+233",
		Name:           "Ghana",
		NameZh:         "加纳",
	},
	{
		Code:           "GR",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+30",
		Name:           "Greece",
		NameZh:         "希腊",
	},
	{
		Code:           "GL",
		Currency:       "DKK",
		CurrencySymbol: "kr",
		Phone:          "+299",
		Name:           "Greenland",
		NameZh:         "格陵兰",
	},
	{
		Code:           "GD",
		Currency:       "XCD",
		CurrencySymbol: "$",
		Phone:          "+1473",
		Name:           "Grenada",
		NameZh:         "格林纳达",
	},
	{
		Code:           "GP",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+590",
		Name:           "Guadeloupe",
		NameZh:         "瓜德罗普",
	},
	{
		Code:           "GU",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+1671",
		Name:           "Guam",
		NameZh:         "关岛",
	},
	{
		Code:           "GT",
		Currency:       "GTQ",
		CurrencySymbol: "Q",
		Phone:          "+502",
		Name:           "Guatemala",
		NameZh:         "危地马拉",
	},
	{
		Code:           "GG",
		Currency:       "GBP",
		CurrencySymbol: "£",
		Phone:          "+44",
		Name:           "Guernsey",
		NameZh:         "根西岛",
	},
	{
		Code:           "GN",
		Currency:       "GNF",
		CurrencySymbol: "FG",
		Phone:          "+224",
		Name:           "Guinea",
		NameZh:         "几内亚",
	},
	{
		Code:           "GW",
		Currency:       "XOF",
		CurrencySymbol: "CFA",
		Phone:          "+245",
		Name:           "Guinea-Bissau",
		NameZh:         "几内亚比绍",
	},
	{
		Code:           "GY",
		Currency:       "GYD",
		CurrencySymbol: "$",
		Phone:          "+592",
		Name:           "Guyana",
		NameZh:         "圭亚那",
	},
	{
		Code:           "HT",
		Currency:       "HTG",
		CurrencySymbol: "G",
		Phone:          "+509",
		Name:           "Haiti",
		NameZh:         "海地",
	},
	{
		Code:           "HM",
		Currency:       "AUD",
		CurrencySymbol: "$",
		Phone:          "+0",
		Name:           "Heard Island and McDonald Islands",
		NameZh:         "赫德岛和麦克唐纳群岛",
	},
	{
		Code:           "VA",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+39",
		Name:           "Holy See (Vatican City)",
		NameZh:         "梵蒂冈城",
	},
	{
		Code:           "HN",
		Currency:       "HNL",
		CurrencySymbol: "L",
		Phone:          "+504",
		Name:           "Honduras",
		NameZh:         "洪都拉斯",
	},
	{
		Code:           "HK",
		Currency:       "HKD",
		CurrencySymbol: "$",
		Phone:          "+852",
		Name:           "Hong Kong SAR China",
		NameZh:         "中国香港特别行政区",
	},
	{
		Code:           "HU",
		Currency:       "HUF",
		CurrencySymbol: "Ft",
		Phone:          "+36",
		Name:           "Hungary",
		NameZh:         "匈牙利",
	},
	{
		Code:           "IS",
		Currency:       "ISK",
		CurrencySymbol: "kr",
		Phone:          "+354",
		Name:           "Iceland",
		NameZh:         "冰岛",
	},
	{
		Code:           "IN",
		Currency:       "INR",
		CurrencySymbol: "₹",
		Phone:          "+91",
		Name:           "India",
		NameZh:         "印度",
	},
	{
		Code:           "ID",
		Currency:       "IDR",
		CurrencySymbol: "Rp",
		Phone:          "+62",
		Name:           "Indonesia",
		NameZh:         "印度尼西亚",
	},
	{
		Code:           "IR",
		Currency:       "IRR",
		CurrencySymbol: "﷼",
		Phone:          "+98",
		Name:           "Iran",
		NameZh:         "伊朗",
	},
	{
		Code:           "IQ",
		Currency:       "IQD",
		CurrencySymbol: "ع.د",
		Phone:          "+964",
		Name:           "Iraq",
		NameZh:         "伊拉克",
	},
	{
		Code:           "IE",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+353",
		Name:           "Ireland",
		NameZh:         "爱尔兰",
	},
	{
		Code:           "IM",
		Currency:       "GBP",
		CurrencySymbol: "£",
		Phone:          "+44",
		Name:           "Isle of Man",
		NameZh:         "马恩岛",
	},
	{
		Code:           "IL",
		Currency:       "ILS",
		CurrencySymbol: "₪",
		Phone:          "+972",
		Name:           "Israel",
		NameZh:         "以色列",
	},
	{
		Code:           "IT",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+39",
		Name:           "Italy",
		NameZh:         "意大利",
	},
	{
		Code:           "JM",
		Currency:       "JMD",
		CurrencySymbol: "J$",
		Phone:          "+1876",
		Name:           "Jamaica",
		NameZh:         "牙买加",
	},
	{
		Code:           "JP",
		Currency:       "JPY",
		CurrencySymbol: "¥",
		Phone:          "+81",
		Name:           "Japan",
		NameZh:         "日本",
	},
	{
		Code:           "JO",
		Currency:       "JOD",
		CurrencySymbol: "JD",
		Phone:          "+962",
		Name:           "Jordan",
		NameZh:         "约旦",
	},
	{
		Code:           "KZ",
		Currency:       "KZT",
		CurrencySymbol: "лв",
		Phone:          "+7",
		Name:           "Kazakhstan",
		NameZh:         "哈萨克斯坦",
	},
	{
		Code:           "KE",
		Currency:       "KES",
		CurrencySymbol: "KSh",
		Phone:          "+254",
		Name:           "Kenya",
		NameZh:         "肯尼亚",
	},
	{
		Code:           "KI",
		Currency:       "AUD",
		CurrencySymbol: "$",
		Phone:          "+686",
		Name:           "Kiribati",
		NameZh:         "基里巴斯",
	},
	{
		Code:           "KW",
		Currency:       "KWD",
		CurrencySymbol: "KD",
		Phone:          "+965",
		Name:           "Kuwait",
		NameZh:         "科威特",
	},
	{
		Code:           "KG",
		Currency:       "KGS",
		CurrencySymbol: "лв",
		Phone:          "+996",
		Name:           "Kyrgyzstan",
		NameZh:         "吉尔吉斯斯坦",
	},
	{
		Code:           "LA",
		Currency:       "LAK",
		CurrencySymbol: "₭",
		Phone:          "+856",
		Name:           "Laos",
		NameZh:         "老挝",
	},
	{
		Code:           "LV",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+371",
		Name:           "Latvia",
		NameZh:         "拉脱维亚",
	},
	{
		Code:           "LB",
		Currency:       "LBP",
		CurrencySymbol: "£",
		Phone:          "+961",
		Name:           "Lebanon",
		NameZh:         "黎巴嫩",
	},
	{
		Code:           "LS",
		Currency:       "LSL",
		CurrencySymbol: "M",
		Phone:          "+266",
		Name:           "Lesotho",
		NameZh:         "莱索托",
	},
	{
		Code:           "LR",
		Currency:       "LRD",
		CurrencySymbol: "$",
		Phone:          "+231",
		Name:           "Liberia",
		NameZh:         "利比里亚",
	},
	{
		Code:           "LY",
		Currency:       "LYD",
		CurrencySymbol: "LD",
		Phone:          "+218",
		Name:           "Libya",
		NameZh:         "利比亚",
	},
	{
		Code:           "LI",
		Currency:       "CHF",
		CurrencySymbol: "CHF",
		Phone:          "+423",
		Name:           "Liechtenstein",
		NameZh:         "列支敦士登",
	},
	{
		Code:           "LT",
		Currency:       "LTL",
		CurrencySymbol: "Lt",
		Phone:          "+370",
		Name:           "Lithuania",
		NameZh:         "立陶宛",
	},
	{
		Code:           "LU",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+352",
		Name:           "Luxembourg",
		NameZh:         "卢森堡",
	},
	{
		Code:           "MO",
		Currency:       "MOP",
		CurrencySymbol: "MOP$",
		Phone:          "+853",
		Name:           "Macau SAR China",
		NameZh:         "中国澳门特别行政区",
	},
	{
		Code:           "MK",
		Currency:       "MKD",
		CurrencySymbol: "ден",
		Phone:          "+389",
		Name:           "Macedonia",
		NameZh:         "北马其顿",
	},
	{
		Code:           "MG",
		Currency:       "MGA",
		CurrencySymbol: "Ar",
		Phone:          "+261",
		Name:           "Madagascar",
		NameZh:         "马达加斯加",
	},
	{
		Code:           "MW",
		Currency:       "MWK",
		CurrencySymbol: "MK",
		Phone:          "+265",
		Name:           "Malawi",
		NameZh:         "马拉维",
	},
	{
		Code:           "MY",
		Currency:       "MYR",
		CurrencySymbol: "RM",
		Phone:          "+60",
		Name:           "Malaysia",
		NameZh:         "马来西亚",
	},
	{
		Code:           "MV",
		Currency:       "MVR",
		CurrencySymbol: "Rf",
		Phone:          "+960",
		Name:           "Maldives",
		NameZh:         "马尔代夫",
	},
	{
		Code:           "ML",
		Currency:       "XOF",
		CurrencySymbol: "CFA",
		Phone:          "+223",
		Name:           "Mali",
		NameZh:         "马里",
	},
	{
		Code:           "MT",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+356",
		Name:           "Malta",
		NameZh:         "马耳他",
	},
	{
		Code:           "MH",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+692",
		Name:           "Marshall Islands",
		NameZh:         "马绍尔群岛",
	},
	{
		Code:           "MQ",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+596",
		Name:           "Martinique",
		NameZh:         "马提尼克",
	},
	{
		Code:           "MR",
		Currency:       "MRO",
		CurrencySymbol: "UM",
		Phone:          "+222",
		Name:           "Mauritania",
		NameZh:         "毛里塔尼亚",
	},
	{
		Code:           "MU",
		Currency:       "MUR",
		CurrencySymbol: "₨",
		Phone:          "+230",
		Name:           "Mauritius",
		NameZh:         "毛里求斯",
	},
	{
		Code:           "YT",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+262",
		Name:           "Mayotte",
		NameZh:         "马约特",
	},
	{
		Code:           "MX",
		Currency:       "MXN",
		CurrencySymbol: "$",
		Phone:          "+52",
		Name:           "Mexico",
		NameZh:         "墨西哥",
	},
	{
		Code:           "FM",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+691",
		Name:           "Micronesia, Federated States Of",
		NameZh:         "密克罗尼西亚联邦",
	},
	{
		Code:           "MI",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+1808",
		Name:           "Midway Island",
		NameZh:         "中途岛",
	},
	{
		Code:           "MD",
		Currency:       "MDL",
		CurrencySymbol: "lei",
		Phone:          "+373",
		Name:           "Moldova",
		NameZh:         "摩尔多瓦",
	},
	{
		Code:           "MC",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+377",
		Name:           "Monaco",
		NameZh:         "摩纳哥",
	},
	{
		Code:           "MN",
		Currency:       "MNT",
		CurrencySymbol: "₮",
		Phone:          "+976",
		Name:           "Mongolia",
		NameZh:         "蒙古",
	},
	{
		Code:           "ME",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+382",
		Name:           "Montenegro",
		NameZh:         "黑山",
	},
	{
		Code:           "MS",
		Currency:       "XCD",
		CurrencySymbol: "$",
		Phone:          "+1664",
		Name:           "Montserrat",
		NameZh:         "蒙特塞拉特",
	},
	{
		Code:           "MA",
		Currency:       "MAD",
		CurrencySymbol: "MAD",
		Phone:          "+212",
		Name:           "Morocco",
		NameZh:         "摩洛哥",
	},
	{
		Code:           "MZ",
		Currency:       "MZN",
		CurrencySymbol: "MT",
		Phone:          "+258",
		Name:           "Mozambique",
		NameZh:         "莫桑比克",
	},
	{
		Code:           "NA",
		Currency:       "NAD",
		CurrencySymbol: "$",
		Phone:          "+264",
		Name:           "Namibia",
		NameZh:         "纳米比亚",
	},
	{
		Code:           "NR",
		Currency:       "AUD",
		CurrencySymbol: "$",
		Phone:          "+674",
		Name:           "Nauru",
		NameZh:         "瑙鲁",
	},
	{
		Code:           "NP",
		Currency:       "NPR",
		CurrencySymbol: "₨",
		Phone:          "+977",
		Name:           "Nepal",
		NameZh:         "尼泊尔",
	},
	{
		Code:           "NL",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+31",
		Name:           "Netherlands",
		NameZh:         "荷兰",
	},
	{
		Code:           "AN",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+599",
		Name:           "Netherlands Antilles",
		NameZh:         "荷属安的列斯",
	},
	{
		Code:           "NC",
		Currency:       "XPF",
		CurrencySymbol: "₣",
		Phone:          "+687",
		Name:           "New Caledonia",
		NameZh:         "新喀里多尼亚",
	},
	{
		Code:           "NZ",
		Currency:       "NZD",
		CurrencySymbol: "$",
		Phone:          "+64",
		Name:           "New Zealand",
		NameZh:         "新西兰",
	},
	{
		Code:           "NI",
		Currency:       "NIO",
		CurrencySymbol: "C$",
		Phone:          "+505",
		Name:           "Nicaragua",
		NameZh:         "尼加拉瓜",
	},
	{
		Code:           "NE",
		Currency:       "XOF",
		CurrencySymbol: "CFA",
		Phone:          "+227",
		Name:           "Niger",
		NameZh:         "尼日尔",
	},
	{
		Code:           "NG",
		Currency:       "NGN",
		CurrencySymbol: "₦",
		Phone:          "+234",
		Name:           "Nigeria",
		NameZh:         "尼日利亚",
	},
	{
		Code:           "NU",
		Currency:       "NZD",
		CurrencySymbol: "$",
		Phone:          "+683",
		Name:           "Niue",
		NameZh:         "纽埃",
	},
	{
		Code:           "NF",
		Currency:       "AUD",
		CurrencySymbol: "$",
		Phone:          "+672",
		Name:           "Norfolk Island",
		NameZh:         "诺福克岛",
	},
	{
		Code:           "KP",
		Currency:       "KPW",
		CurrencySymbol: "₩",
		Phone:          "+850",
		Name:           "North Korea",
		NameZh:         "朝鲜",
	},
	{
		Code:           "MP",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+1670",
		Name:           "Northern Mariana Islands",
		NameZh:         "北马里亚纳群岛",
	},
	{
		Code:           "NO",
		Currency:       "NOK",
		CurrencySymbol: "kr",
		Phone:          "+47",
		Name:           "Norway",
		NameZh:         "挪威",
	},
	{
		Code:           "OM",
		Currency:       "OMR",
		CurrencySymbol: "﷼",
		Phone:          "+968",
		Name:           "Oman",
		NameZh:         "阿曼",
	},
	{
		Code:           "PK",
		Currency:       "PKR",
		CurrencySymbol: "₨",
		Phone:          "+92",
		Name:           "Pakistan",
		NameZh:         "巴基斯坦",
	},
	{
		Code:           "PW",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+680",
		Name:           "Palau",
		NameZh:         "帕劳",
	},
	{
		Code:           "PA",
		Currency:       "PAB",
		CurrencySymbol: "B/.",
		Phone:          "+507",
		Name:           "Panama",
		NameZh:         "巴拿马",
	},
	{
		Code:           "PG",
		Currency:       "PGK",
		CurrencySymbol: "K",
		Phone:          "+675",
		Name:           "Papua New Guinea",
		NameZh:         "巴布亚新几内亚",
	},
	{
		Code:           "PY",
		Currency:       "PYG",
		CurrencySymbol: "Gs",
		Phone:          "+595",
		Name:           "Paraguay",
		NameZh:         "巴拉圭",
	},
	{
		Code:           "PE",
		Currency:       "PEN",
		CurrencySymbol: "S/.",
		Phone:          "+51",
		Name:           "Peru",
		NameZh:         "秘鲁",
	},
	{
		Code:           "PH",
		Currency:       "PHP",
		CurrencySymbol: "₱",
		Phone:          "+63",
		Name:           "Philippines",
		NameZh:         "菲律宾",
	},
	{
		Code:           "PN",
		Currency:       "NZD",
		CurrencySymbol: "$",
		Phone:          "+870",
		Name:           "Pitcairn Islands",
		NameZh:         "皮特凯恩群岛",
	},
	{
		Code:           "PL",
		Currency:       "PLN",
		CurrencySymbol: "zł",
		Phone:          "+48",
		Name:           "Poland",
		NameZh:         "波兰",
	},
	{
		Code:           "PT",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+351",
		Name:           "Portugal",
		NameZh:         "葡萄牙",
	},
	{
		Code:           "PR",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+1787",
		Name:           "Puerto Rico",
		NameZh:         "波多黎各",
	},
	{
		Code:           "QA",
		Currency:       "QAR",
		CurrencySymbol: "﷼",
		Phone:          "+974",
		Name:           "Qatar",
		NameZh:         "卡塔尔",
	},
	{
		Code:           "RE",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+262",
		Name:           "Reunion",
		NameZh:         "留尼汪",
	},
	{
		Code:           "RO",
		Currency:       "RON",
		CurrencySymbol: "lei",
		Phone:          "+40",
		Name:           "Romania",
		NameZh:         "罗马尼亚",
	},
	{
		Code:           "RU",
		Currency:       "RUB",
		CurrencySymbol: "₽",
		Phone:          "+7",
		Name:           "Russia",
		NameZh:         "俄罗斯",
	},
	{
		Code:           "RW",
		Currency:       "RWF",
		CurrencySymbol: "R₣",
		Phone:          "+250",
		Name:           "Rwanda",
		NameZh:         "卢旺达",
	},
	{
		Code:           "BL",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+590",
		Name:           "Saint Barthelemy",
		NameZh:         "圣巴泰勒米",
	},
	{
		Code:           "SH",
		Currency:       "SHP",
		CurrencySymbol: "£",
		Phone:          "+290",
		Name:           "Saint Helena",
		NameZh:         "圣赫勒拿",
	},
	{
		Code:           "KN",
		Currency:       "XCD",
		CurrencySymbol: "$",
		Phone:          "+1869",
		Name:           "Saint Kitts and Nevis",
		NameZh:         "圣基茨和尼维斯",
	},
	{
		Code:           "LC",
		Currency:       "XCD",
		CurrencySymbol: "$",
		Phone:          "+1758",
		Name:           "Saint Lucia",
		NameZh:         "圣卢西亚",
	},
	{
		Code:           "MF",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+1",
		Name:           "Saint Martin",
		NameZh:         "圣马丁",
	},
	{
		Code:           "PM",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+508",
		Name:           "Saint Pierre and Miquelon",
		NameZh:         "圣皮埃尔和密克隆",
	},
	{
		Code:           "ST",
		Currency:       "STD",
		CurrencySymbol: "Db",
		Phone:          "+239",
		Name:           "Saint tome and principle",
		NameZh:         "圣多美和普林西比",
	},
	{
		Code:           "VC",
		Currency:       "XCD",
		CurrencySymbol: "$",
		Phone:          "+1784",
		Name:           "Saint Vincent and the Grenadines",
		NameZh:         "圣文森特和格林纳丁斯",
	},
	{
		Code:           "WS",
		Currency:       "WST",
		CurrencySymbol: "WS$",
		Phone:          "+684",
		Name:           "Samoa",
		NameZh:         "萨摩亚",
	},
	{
		Code:           "SM",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+378",
		Name:           "San Marino",
		NameZh:         "圣马力诺",
	},
	{
		Code:           "SA",
		Currency:       "SAR",
		CurrencySymbol: "﷼",
		Phone:          "+966",
		Name:           "Saudi Arabia",
		NameZh:         "沙特阿拉伯",
	},
	{
		Code:           "SN",
		Currency:       "XOF",
		CurrencySymbol: "CFA",
		Phone:          "+221",
		Name:           "Senegal",
		NameZh:         "塞内加尔",
	},
	{
		Code:           "RS",
		Currency:       "RSD",
		CurrencySymbol: "Дин.",
		Phone:          "+381",
		Name:           "Serbia",
		NameZh:         "塞尔维亚",
	},
	{
		Code:           "SC",
		Currency:       "SCR",
		CurrencySymbol: "₨",
		Phone:          "+248",
		Name:           "Seychelles",
		NameZh:         "塞舌尔",
	},
	{
		Code:           "SL",
		Currency:       "SLL",
		CurrencySymbol: "Le",
		Phone:          "+232",
		Name:           "Sierra Leone",
		NameZh:         "塞拉利昂",
	},
	{
		Code:           "SG",
		Currency:       "SGD",
		CurrencySymbol: "$",
		Phone:          "+65",
		Name:           "Singapore",
		NameZh:         "新加坡",
	},
	{
		Code:           "SX",
		Currency:       "ANG",
		CurrencySymbol: "ƒ",
		Phone:          "+721",
		Name:           "Sint Maarten",
		NameZh:         "荷属圣马丁",
	},
	{
		Code:           "SK",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+421",
		Name:           "Slovakia",
		NameZh:         "斯洛伐克",
	},
	{
		Code:           "SI",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+386",
		Name:           "Slovenia",
		NameZh:         "斯洛文尼亚",
	},
	{
		Code:           "SB",
		Currency:       "SBD",
		CurrencySymbol: "$",
		Phone:          "+677",
		Name:           "Solomon Islands",
		NameZh:         "所罗门群岛",
	},
	{
		Code:           "ZA",
		Currency:       "ZAR",
		CurrencySymbol: "R",
		Phone:          "+27",
		Name:           "South Africa",
		NameZh:         "南非",
	},
	{
		Code:           "GS",
		Currency:       "GBP",
		CurrencySymbol: "£",
		Phone:          "+500",
		Name:           "South Georgia and the South Sandwich Islands",
		NameZh:         "南乔治亚和南桑威奇群岛",
	},
	{
		Code:           "KR",
		Currency:       "KRW",
		CurrencySymbol: "₩",
		Phone:          "+82",
		Name:           "South Korea",
		NameZh:         "韩国",
	},
	{
		Code:           "SS",
		Currency:       "SSP",
		CurrencySymbol: "£",
		Phone:          "+211",
		Name:           "South Sudan",
		NameZh:         "南苏丹",
	},
	{
		Code:           "ES",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+34",
		Name:           "Spain",
		NameZh:         "西班牙",
	},
	{
		Code:           "LK",
		Currency:       "LKR",
		CurrencySymbol: "₨",
		Phone:          "+94",
		Name:           "Sri Lanka",
		NameZh:         "斯里兰卡",
	},
	{
		Code:           "SD",
		Currency:       "SDG",
		CurrencySymbol: "ج.س.",
		Phone:          "+249",
		Name:           "Sudan",
		NameZh:         "苏丹",
	},
	{
		Code:           "SR",
		Currency:       "SRD",
		CurrencySymbol: "$",
		Phone:          "+597",
		Name:           "Suriname",
		NameZh:         "苏里南",
	},
	{
		Code:           "SJ",
		Currency:       "NOK",
		CurrencySymbol: "kr",
		Phone:          "+47",
		Name:           "Svalbard",
		NameZh:         "斯瓦尔巴",
	},
	{
		Code:           "SZ",
		Currency:       "SZL",
		CurrencySymbol: "E",
		Phone:          "+268",
		Name:           "Swaziland",
		NameZh:         "斯威士兰",
	},
	{
		Code:           "SE",
		Currency:       "SEK",
		CurrencySymbol: "kr",
		Phone:          "+46",
		Name:           "Sweden",
		NameZh:         "瑞典",
	},
	{
		Code:           "CH",
		Currency:       "CHF",
		CurrencySymbol: "CHF",
		Phone:          "+41",
		Name:           "Switzerland",
		NameZh:         "瑞士",
	},
	{
		Code:           "SY",
		Currency:       "SYP",
		CurrencySymbol: "£",
		Phone:          "+963",
		Name:           "Syria",
		NameZh:         "叙利亚",
	},
	{
		Code:           "TW",
		Currency:       "TWD",
		CurrencySymbol: "NT$",
		Phone:          "+886",
		Name:           "Taiwan",
		NameZh:         "台湾",
	},
	{
		Code:           "TJ",
		Currency:       "TJS",
		CurrencySymbol: "SM",
		Phone:          "+992",
		Name:           "Tajikistan",
		NameZh:         "塔吉克斯坦",
	},
	{
		Code:           "TZ",
		Currency:       "TZS",
		CurrencySymbol: "TSh",
		Phone:          "+255",
		Name:           "Tanzania",
		NameZh:         "坦桑尼亚",
	},
	{
		Code:           "TH",
		Currency:       "THB",
		CurrencySymbol: "฿",
		Phone:          "+66",
		Name:           "Thailand",
		NameZh:         "泰国",
	},
	{
		Code:           "TG",
		Currency:       "XOF",
		CurrencySymbol: "CFA",
		Phone:          "+228",
		Name:           "Togo",
		NameZh:         "多哥",
	},
	{
		Code:           "TK",
		Currency:       "NZD",
		CurrencySymbol: "$",
		Phone:          "+690",
		Name:           "Tokelau",
		NameZh:         "托克劳",
	},
	{
		Code:           "TO",
		Currency:       "TOP",
		CurrencySymbol: "T$",
		Phone:          "+676",
		Name:           "Tonga",
		NameZh:         "汤加",
	},
	{
		Code:           "TT",
		Currency:       "TTD",
		CurrencySymbol: "TT$",
		Phone:          "+1868",
		Name:           "Trinidad and Tobago",
		NameZh:         "特立尼达和多巴哥",
	},
	{
		Code:           "TN",
		Currency:       "TND",
		CurrencySymbol: "د.ت",
		Phone:          "+216",
		Name:           "Tunisia",
		NameZh:         "突尼斯",
	},
	{
		Code:           "TR",
		Currency:       "TRY",
		CurrencySymbol: "₺",
		Phone:          "+90",
		Name:           "Turkey",
		NameZh:         "土耳其",
	},
	{
		Code:           "TM",
		Currency:       "TMT",
		CurrencySymbol: "T",
		Phone:          "+7370",
		Name:           "Turkmenistan",
		NameZh:         "土库曼斯坦",
	},
	{
		Code:           "TC",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+1649",
		Name:           "Turks and Caicos Islands",
		NameZh:         "特克斯和凯科斯群岛",
	},
	{
		Code:           "TV",
		Currency:       "AUD",
		CurrencySymbol: "$",
		Phone:          "+688",
		Name:           "Tuvalu",
		NameZh:         "图瓦卢",
	},
	{
		Code:           "UG",
		Currency:       "UGX",
		CurrencySymbol: "USh",
		Phone:          "+256",
		Name:           "Uganda",
		NameZh:         "乌干达",
	},
	{
		Code:           "UA",
		Currency:       "UAH",
		CurrencySymbol: "₴",
		Phone:          "+380",
		Name:           "Ukraine",
		NameZh:         "乌克兰",
	},
	{
		Code:           "AE",
		Currency:       "AED",
		CurrencySymbol: "د.إ",
		Phone:          "+971",
		Name:           "United Arab Emirates",
		NameZh:         "阿拉伯联合酋长国",
	},
	{
		Code:           "UK",
		Currency:       "AED",
		CurrencySymbol: "د.إ",
		Phone:          "+44",
		Name:           "United Kingdom",
		NameZh:         "英国",
	},
	{
		Code:           "UM",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+1",
		Name:           "United States Minor Outlying Islands",
		NameZh:         "美国本土外小岛屿",
	},
	{
		Code:           "US",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+1",
		Name:           "United States",
		NameZh:         "美国",
	},
	{
		Code:           "UY",
		Currency:       "UYU",
		CurrencySymbol: "$U",
		Phone:          "+598",
		Name:           "Uruguay",
		NameZh:         "乌拉圭",
	},
	{
		Code:           "UZ",
		Currency:       "UZS",
		CurrencySymbol: "лв",
		Phone:          "+998",
		Name:           "Uzbekistan",
		NameZh:         "乌兹别克斯坦",
	},
	{
		Code:           "VU",
		Currency:       "VUV",
		CurrencySymbol: "VT",
		Phone:          "+678",
		Name:           "Vanuatu",
		NameZh:         "瓦努阿图",
	},
	{
		Code:           "VE",
		Currency:       "VEF",
		CurrencySymbol: "Bs",
		Phone:          "+58",
		Name:           "Venezuela",
		NameZh:         "委内瑞拉",
	},
	{
		Code:           "VN",
		Currency:       "VND",
		CurrencySymbol: "₫",
		Phone:          "+84",
		Name:           "Vietnam",
		NameZh:         "越南",
	},
	{
		Code:           "VI",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+1340",
		Name:           "Virgin Islands",
		NameZh:         "美属维尔京群岛",
	},
	{
		Code:           "WF",
		Currency:       "XPF",
		CurrencySymbol: "₣",
		Phone:          "+681",
		Name:           "Wallis and Futuna",
		NameZh:         "瓦利斯和富图纳",
	},
	{
		Code:           "EH",
		Currency:       "MAD",
		CurrencySymbol: "MAD",
		Phone:          "+212",
		Name:           "Western Sahara",
		NameZh:         "西撒哈拉",
	},
	{
		Code:           "YE",
		Currency:       "YER",
		CurrencySymbol: "﷼",
		Phone:          "+967",
		Name:           "Yemen",
		NameZh:         "也门",
	},
	{
		Code:           "ZM",
		Currency:       "ZMK",
		CurrencySymbol: "﷼",
		Phone:          "+260",
		Name:           "Zambia",
		NameZh:         "赞比亚",
	},
	{
		Code:           "ZW",
		Currency:       "ZWL",
		CurrencySymbol: "﷼",
		Phone:          "+263",
		Name:           "Zimbabwe",
		NameZh:         "津巴布韦",
	},
}
